# Generated by Django 5.1.3 on 2025-02-09 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id_mat', models.AutoField(primary_key=True, serialize=False)),
                ('nom_mat', models.CharField(max_length=100)),
                ('tipo_mat', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('foto_mat', models.FileField(blank=True, null=True, upload_to='materiales')),
                ('prec_unidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField()),
                ('cantidad_mat', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id_ord', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ord', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Recibida', 'Recibida')], default='Pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Suministradores',
            fields=[
                ('id_sumi', models.AutoField(primary_key=True, serialize=False)),
                ('nom_sumi', models.CharField(max_length=100)),
                ('contact_sumi', models.CharField(max_length=10)),
                ('direcc_sumi', models.CharField(max_length=100)),
                ('telf_sumi', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Existencias',
            fields=[
                ('id_exis', models.AutoField(primary_key=True, serialize=False)),
                ('cant_disp', models.PositiveIntegerField()),
                ('tipo_mov', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], default='Entrada', max_length=20)),
                ('fech_exis', models.DateField()),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='Materiales.materiales')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='Materiales.ordenes')),
            ],
        ),
        migrations.AddField(
            model_name='ordenes',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='Materiales.suministradores'),
        ),
    ]
