# Generated by Django 5.1.3 on 2025-02-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suministradores',
            name='contact_sumi',
        ),
    ]
