# Generated by Django 5.1.3 on 2025-02-09 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0002_remove_suministradores_contact_sumi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenes',
            old_name='proveedor',
            new_name='suministrador',
        ),
    ]
