# Generated by Django 5.1.3 on 2025-02-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0003_rename_proveedor_ordenes_suministrador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='cantidad_mat',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
