# Generated by Django 5.1.3 on 2025-02-10 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0004_alter_materiales_cantidad_mat'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='existencias',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='Materiales.materiales'),
        ),
        migrations.AlterField(
            model_name='existencias',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='Materiales.ordenes'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
