# Generated by Django 5.1.3 on 2025-02-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0005_materiales_stock_alter_existencias_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiales',
            name='cantidad_mat',
        ),
    ]
