# Generated by Django 5.1.3 on 2025-02-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiales', '0006_remove_materiales_cantidad_mat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='prec_unidad',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
